services:
  - type: web
    name: attorney-scheduler-server
    env: node
    plan: free
    rootDir: server
    buildCommand: "npm install && npm run migrate"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

  - type: static
    name: attorney-scheduler-client
    rootDir: client
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
